import { Resend } from "resend";

import { env } from "./env";

export const resend = new Resend(env.server.RESEND_API_KEY);

interface ProjectMailParams {
  projectCode: string;
  to: string | string[];
  subject: string;
  html: string;
  text?: string;
}

export async function sendProjectMail({ projectCode, to, subject, html, text }: ProjectMailParams) {
  const prefixedSubject = `[Project: ${projectCode}] ${subject}`;

  await resend.emails.send({
    from: env.server.RESEND_FROM_EMAIL,
    to: Array.isArray(to) ? to : [to],
    subject: prefixedSubject,
    html,
    text,
  });
}

interface ResetPasswordParams {
  to: string;
  token: string;
}

export async function sendPasswordResetEmail({ to, token }: ResetPasswordParams) {
  const resetUrl = `${env.server.APP_BASE_URL}/reset-password?token=${token}`;
  const html = `
    <p>We received a request to reset your Intermax Management App password.</p>
    <p><a href="${resetUrl}">Reset Password</a></p>
    <p>If you did not request this, you can ignore this email.</p>
  `;

  await resend.emails.send({
    from: env.server.RESEND_FROM_EMAIL,
    to: [to],
    subject: "Intermax Management App - Reset Password",
    html,
    text: `Use the link to reset your password: ${resetUrl}`,
  });
}

interface TaskAssignmentMailParams {
  to: string;
  taskTitle: string;
  start: Date;
  end: Date;
  description?: string | null;
  projectName?: string | null;
  assignerName?: string | null;
  taskId?: string;
}

const dateFormatter = new Intl.DateTimeFormat("en-US", {
  dateStyle: "medium",
  timeStyle: "short",
});

export async function sendTaskAssignmentEmail({
  to,
  taskTitle,
  start,
  end,
  description,
  projectName,
  assignerName,
  taskId,
}: TaskAssignmentMailParams) {
  const startLabel = dateFormatter.format(start);
  const endLabel = dateFormatter.format(end);
  const projectLine = projectName ? `<p><strong>Project:</strong> ${projectName}</p>` : "";
  const descriptionLine = description ? `<p><strong>Details:</strong><br/>${description.replace(/\n/g, "<br/>")}</p>` : "";
  const assigner = assignerName ? `${assignerName}` : "Your coordinator";
  const taskUrl = taskId ? `${env.server.APP_BASE_URL}/tasks?task=${taskId}` : `${env.server.APP_BASE_URL}/tasks`;

  const html = `
    <p>${assigner} has assigned you a new task.</p>
    <p><strong>Task:</strong> ${taskTitle}</p>
    ${projectLine}
    <p><strong>Starts:</strong> ${startLabel}<br/><strong>Ends:</strong> ${endLabel}</p>
    ${descriptionLine}
    <p><a href="${taskUrl}">Open this task</a> to review the requirements and update progress.</p>
    <p style="margin-top:24px; font-size:12px; color:#6b7280;">This notification was generated by Intermax Management App.</p>
  `;

  const textLines = [
    `${assigner} has assigned you a new task.`,
    ``,
    `Task: ${taskTitle}`,
    projectName ? `Project: ${projectName}` : null,
    `Starts: ${startLabel}`,
    `Ends: ${endLabel}`,
    description ? `\nDetails:\n${description}` : null,
    ``,
    `Open the task: ${taskUrl}`,
  ].filter(Boolean);
  const text = textLines.join("\n");
  await resend.emails.send({
    from: env.server.RESEND_FROM_EMAIL,
    to: [to],
    subject: `New task assigned: ${taskTitle}`,
    html,
    text,
  });
}
